repos:
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["-q", "-r", "."]
  - repo: https://github.com/returntocorp/semgrep
    rev: v1.133.0
    hooks:
      - id: semgrep
  - repo: local
    hooks:
      - id: safety
        name: safety
        entry: python -m safety check --full-report --file requirements.txt
        language: system
        pass_filenames: false
      - id: trufflehog
        name: trufflehog
        entry: /root/.pyenv/versions/3.12.10/bin/trufflehog --json .
        language: system
        pass_filenames: false
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
  - repo: https://github.com/GitGuardian/ggshield
    rev: v1.42.0
    hooks:
      - id: ggshield
